### ISSUE TITLE
Crash on verifying

### ISSUE THREAD

**Issue by denysdovhan** [sethvincent/javascripting#144]
There is a critical bug.

When I try to verify something, it throw error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module './lib/footer.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/javascripting/lib/problem.js:42:9)
    at /usr/lib/node_modules/javascripting/lib/compare-solution.js:27:7
    at /usr/lib/node_modules/javascripting/lib/run-solution.js:9:10
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
```

**UPD:** I've tried to check out here e1101b2e2df0eae179a3224510d1a4e1d273b0a2. All works fine here. So, maybe something goes wrong with @martinheidegger's commits.

**Comment by martinheidegger** [comment]
I just pushed a fix. @sethvincent @SomeoneWeird Do you mind publishing it to npm?

**Comment by sethvincent** [comment]
published!

**Comment by martinheidegger** [comment]
:+1:

**Comment by denysdovhan** [comment]
Thanks, you saved my time.
