### ISSUE TITLE
Cannot switch to old mode now

### ISSUE THREAD

**Issue by sethvincent** [sethvincent/javascripting#75]
```
_stream_readable.js:749
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:749:11)
    at ReadStream.Readable.resume (_stream_readable.js:734:3)
    at showMenu (/Users/sethvincent/workspace/javascript-modules/nodeschool/javascripting/node_modules/workshopper-adventure/menu.js:90:17)
    at showMenu (/Users/sethvincent/workspace/javascript-modules/nodeschool/javascripting/node_modules/workshopper-adventure/exerciseMenu.js:29:10)
    at Adventure.printMenu (/Users/sethvincent/workspace/javascript-modules/nodeschool/javascripting/node_modules/workshopper-adventure/adventure.js:462:14)
    at Adventure.execute (/Users/sethvincent/workspace/javascript-modules/nodeschool/javascripting/node_modules/workshopper-adventure/adventure.js:203:8)
    at Object.<anonymous> (/Users/sethvincent/workspace/javascript-modules/nodeschool/javascripting/index.js:19:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Looks like it is related to process.stdin.pause() / process.stdin.resume()  in the menu.js file of workshopper-adventure

**Comment by sethvincent** [comment]
fixed by updating workshopper-adventure
